# Generated by Django 6.0.4 on 2026-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded image', upload_to='projects/images/%Y/%m/%d/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name / short title', max_length=255, verbose_name='Title')),
                ('address', models.CharField(blank=True, help_text='Full physical or legal address', max_length=500, verbose_name='Address')),
                ('documents_storage', models.URLField(blank=True, help_text='Link to folder with documents', max_length=500, null=True, verbose_name='Documents storage')),
                ('expenses_sheet', models.URLField(blank=True, help_text='Link to budget / expenses table', max_length=500, null=True, verbose_name='Expenses sheet')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('images', models.ManyToManyField(blank=True, related_name='projects', to='projects.image', verbose_name='Images')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='projects_pr_created_775fe7_idx'), models.Index(fields=['title'], name='projects_pr_title_ba614c_idx')],
            },
        ),
    ]
