# Generated by Django 6.0.4 on 2026-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Загрузить одно или несколько изображений', upload_to='projects/images/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес по ЕГРН / ориентир', max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Статус проекта / описание', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='documents_storage',
            field=models.URLField(blank=True, help_text='Ссылка на папку или облачное хранилище с документами', max_length=500, null=True, verbose_name='Documents storage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='expenses_sheet',
            field=models.URLField(blank=True, help_text='Ссылка на таблицу с расходами', max_length=500, null=True, verbose_name='Expenses sheet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Название проекта', max_length=255, verbose_name='Title'),
        ),
    ]
